### ISSUE TITLE
Find/Implement A Library for binary message packing in Python

### ISSUE THREAD

**Issue by jacksonmowry** [utk-cs340-fall24/notJSON#55]
Find/Implement a library that will allow us to pack a custom message of bytes in the exact same manner as we would in c

**Comment by MikJak75** [comment]
Here are some possible tools we can use to implement binary message packing python:

Option 1 (Python struct Library):
https://docs.python.org/3/library/struct.html

Option 2 (Python cstruct library):
https://github.com/andreax79/python-cstruct

Option 2 seems to have more functionality and could potentially allow for us to use c style struct definitions to create structs in python. Option 1 seems simpler and easier to use
